const Span = @import("../proof_script.zig").Span;

pub const DiagnosticKind = enum {
    generic,
    missing_proof_block,
    extra_proof_block,
    theorem_name_mismatch,
    duplicate_rule_name,
    parse_assertion,
    parse_binding,
    parse_fresh,
    inference_failed,
    unknown_rule,
    unknown_binder_name,
    duplicate_binder_assignment,
    missing_binder_assignment,
    ref_count_mismatch,
    unknown_hypothesis_ref,
    unknown_label,
    hypothesis_mismatch,
    conclusion_mismatch,
    duplicate_label,
    empty_proof_block,
    final_line_mismatch,
};

pub const Diagnostic = struct {
    kind: DiagnosticKind,
    err: anyerror,
    theorem_name: ?[]const u8 = null,
    block_name: ?[]const u8 = null,
    line_label: ?[]const u8 = null,
    rule_name: ?[]const u8 = null,
    name: ?[]const u8 = null,
    expected_name: ?[]const u8 = null,
    span: ?Span = null,
};

pub fn diagnosticSummary(diag: Diagnostic) []const u8 {
    return switch (diag.kind) {
        .generic => compilerErrorSummary(diag.err),
        .missing_proof_block => "missing proof block for theorem",
        .extra_proof_block => "extra proof block with no matching theorem",
        .theorem_name_mismatch => "proof block name does not match the theorem",
        .duplicate_rule_name => "duplicate rule name",
        .parse_assertion => "could not parse proof line assertion",
        .parse_binding => "could not parse binder assignment",
        .parse_fresh => compilerErrorSummary(diag.err),
        .inference_failed => compilerErrorSummary(diag.err),
        .unknown_rule => "unknown rule in proof line",
        .unknown_binder_name => "unknown binder name in rule application",
        .duplicate_binder_assignment => "duplicate binder assignment in rule application",
        .missing_binder_assignment => "missing binder assignment in rule application",
        .ref_count_mismatch => "wrong number of references for rule application",
        .unknown_hypothesis_ref => "unknown theorem hypothesis reference",
        .unknown_label => "unknown proof line label",
        .hypothesis_mismatch => "rule reference does not match the expected hypothesis",
        .conclusion_mismatch => "proof line assertion does not match the rule conclusion",
        .duplicate_label => "duplicate proof line label",
        .empty_proof_block => "proof block is empty",
        .final_line_mismatch => "last proof line does not prove the theorem conclusion",
    };
}

fn compilerErrorSummary(err: anyerror) []const u8 {
    return switch (err) {
        error.BoundnessMismatch => "binding does not satisfy the rule's " ++
            "bound-variable constraint",
        error.SortMismatch => "binding does not satisfy the rule's sort constraint",
        error.UnifyMismatch,
        error.TermMismatch,
        error.ExpectedTermApp,
        error.UnifyStackNotEmpty,
        error.HypCountMismatch,
        => "could not infer omitted rule arguments from the line and refs",
        error.AmbiguousAcuiMatch => "omitted rule arguments are ambiguous after structural " ++
            "or def-aware matching",
        error.UnknownTheoremVariable => "binding refers to a theorem variable that is not in scope",
        error.DuplicateRuleName => "duplicate rule name",
        error.DuplicateViewAnnotation => "multiple @view annotations were attached to one rule",
        error.InvalidViewAnnotation => "could not parse @view annotation",
        error.ViewHypCountMismatch => "@view hypothesis count does not match the rule",
        error.ViewConclusionMismatch => "@view conclusion does not match the proof line assertion",
        error.ViewHypothesisMismatch => "@view hypotheses do not match the cited refs",
        error.ViewBindingConflict => "@view inference conflicts with an explicit binding",
        error.RecoverWithoutView => "@recover requires a preceding @view on the same rule",
        error.InvalidRecoverAnnotation => "@recover expects four binder names: target source " ++
            "pattern hole",
        error.UnknownRecoverBinder => "@recover refers to a binder name not present in the view",
        error.RecoverTargetNotRuleBinder => "@recover target must be a real rule binder",
        error.RecoverSortMismatch => "@recover target and hole binders must have the same sort",
        error.RecoverHoleNotFound => "@recover could not find the hole binder in the pattern expr",
        error.RecoverConflict => "@recover found inconsistent candidates for the target " ++
            "binder",
        error.RecoverStructureMismatch => "@recover source expr does not match the pattern structure",
        error.AbstractWithoutView => "@abstract requires a preceding @view on the same rule",
        error.InvalidAbstractAnnotation => "@abstract expects six binder names: target left " ++
            "right hole left_plug right_plug",
        error.UnknownAbstractBinder => "@abstract refers to a binder name not present in the view",
        error.AbstractTargetNotRuleBinder => "@abstract target must be a real rule binder",
        error.AbstractHoleSortMismatch => "@abstract target and hole binders must have the same sort",
        error.AbstractPlugSortMismatch => "@abstract hole and plug binders must have the same sort",
        error.AbstractNoPlugOccurrence => "@abstract could not find the plug pair in the source exprs",
        error.AbstractConflict => "@abstract found a context that conflicts with the target binder",
        error.AbstractStructureMismatch => "@abstract source exprs do not match outside the plug pair",
        error.UnknownTermAnnotation => "unknown term-level annotation",
        error.DummyAnnotationRemoved => "@dummy was removed; use @fresh instead",
        error.InvalidFreshAnnotation => "@fresh expects exactly one real rule binder name",
        error.UnknownFreshBinder => "@fresh target must be a real rule binder",
        error.DuplicateFreshBinder => "multiple @fresh annotations were attached to one rule binder",
        error.FreshRequiresBoundBinder => "@fresh target must be a bound rule binder",
        error.FreshStrictSort => "@fresh cannot target a binder in a strict sort",
        error.FreshFreeSort => "@fresh cannot target a binder in a free sort",
        error.FreshNoAvailableVar => "@fresh could not find an available @vars token",
        error.InvalidVarsAnnotation => "@vars expects one or more raw math tokens",
        error.VarsStrictSort => "@vars cannot be used on a strict sort",
        error.VarsFreeSort => "@vars cannot be used on a free sort",
        error.DuplicateVarsToken => "duplicate @vars token across sorts",
        error.VarsTokenCollision => "@vars token collides with an existing term, notation, " ++
            "or formula marker",
        error.DependencySlotExhausted => "theorem exceeded the 55 tracked bound-variable dependency slots",
        error.UnresolvedDummyWitness => "matched rule through hidden def structure, but omitted " ++
            "binders contain unresolved hidden-dummy witnesses",
        else => @errorName(err),
    };
}
